# Generated by Django 5.2.5 on 2025-08-14 21:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Nome"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Nome")),
                ("logo", models.CharField(max_length=200, verbose_name="Logo")),
                ("url", models.CharField(max_length=100, verbose_name="Link")),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Preço")),
                ("is_available", models.BooleanField()),
                ("url", models.CharField(max_length=200, verbose_name="Link")),
                ("photo", models.CharField(max_length=200, verbose_name="Foto")),
                ("category", models.CharField(max_length=50, verbose_name="Categoria")),
                (
                    "sub_group",
                    models.CharField(max_length=50, verbose_name="Sub-grupo"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.store"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalStock",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("price", models.FloatField(verbose_name="Preço")),
                ("is_available", models.BooleanField()),
                ("url", models.CharField(max_length=200, verbose_name="Link")),
                ("photo", models.CharField(max_length=200, verbose_name="Foto")),
                ("category", models.CharField(max_length=50, verbose_name="Categoria")),
                (
                    "sub_group",
                    models.CharField(max_length=50, verbose_name="Sub-grupo"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical stock",
                "verbose_name_plural": "historical stocks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
